Pin to googleauth-1.15.0
The bump to 1.15.1 started causing PagerDuty sync issues: https://github.com/alphagov/govuk-rota-generator/actions/runs/18586416313/job/52991628914

```
NoMethodError: undefined method `rewind' for an instance of PretendFile (NoMethodError)

        json_key_io.rewind # Rewind the stream so it can be read again.
                   ^^^^^^^
/home/runner/work/govuk-rota-generator/govuk-rota-generator/vendor/bundle/ruby/3.3.0/gems/googleauth-1.15.1/lib/googleauth/credentials_loader.rb:169:in `load_and_verify_json_key_type'
/home/runner/work/govuk-rota-generator/govuk-rota-generator/vendor/bundle/ruby/3.3.0/gems/googleauth-1.15.1/lib/googleauth/service_account.rb:69:in `make_creds'
/home/runner/work/govuk-rota-generator/govuk-rota-generator/lib/google_sheet.rb:39:in `initialize'
/home/runner/work/govuk-rota-generator/govuk-rota-generator/bin/sync_pagerduty.rb:21:in `new'
/home/runner/work/govuk-rota-generator/govuk-rota-generator/bin/sync_pagerduty.rb:21:in `execute'
/home/runner/work/govuk-rota-generator/govuk-rota-generator/Rakefile:5:in `block in <top (required)>'
/home/runner/work/govuk-rota-generator/govuk-rota-generator/vendor/bundle/ruby/3.3.0/gems/rake-13.3.0/exe/rake:27:in `<top (required)>'
/opt/hostedtoolcache/Ruby/3.3.6/x64/bin/bundle:25:in `load'
/opt/hostedtoolcache/Ruby/3.3.6/x64/bin/bundle:25:in `<main>'
```

So let's just stick with what we know works.